# Generated by Django 3.2.15 on 2023-06-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
    ]
